# ==== black ====
[tool.black]
line-length = 119
target-version = ['py311']

# ==== isort ====
[tool.isort]
profile = "black"
line_length = 119

# ==== flake8 ====
[tool.flake8]
max-line-length = 119
