_create_users_sql_table = """
    CREATE TABLE IF NOT EXISTS users (
        id SERIAL PRIMARY KEY,
        _id VARCHAR(255) NULL,
        name VARCHAR(255) NULL,
        email VARCHAR(255) NULL,
        about TEXT,
        phoneNumber VARCHAR(255) NULL,
        criminalStatus VARCHAR(255) NULL,
        isClient BOOLEAN,
        IsSpecialist BOOLEAN,
        isValidCertification BOOLEAN,
        isActive BOOLEAN,
        isDeleted BOOLEAN,
        registerType VARCHAR(255) NULL,
        profileImg_url VARCHAR(255) NULL,
        licenseImg_url VARCHAR(255) NULL,
        insuranceImg_url VARCHAR(255) NULL,
        date TIMESTAMP NULL,
        __v SMALLINT,
        hasServices_refuel_name VARCHAR(255) NULL,
        hasServices_refuel_type VARCHAR(255) NULL,
        hasServices_refuel_isVerified BOOLEAN,
        hasServices_refuel_isApproved BOOLEAN,
        hasServices_tire_change_name VARCHAR(255) NULL,
        hasServices_tire_change_type VARCHAR(255) NULL,
        hasServices_tire_change_isVerified BOOLEAN,
        hasServices_tire_change_isApproved BOOLEAN,
        hasServices_tire_change_certificate_uri VARCHAR(255) NULL,
        hasServices_jump_name VARCHAR(255) NULL,
        hasServices_jump_type VARCHAR(255) NULL,
        hasServices_jump_isVerified BOOLEAN,
        hasServices_jump_isApproved BOOLEAN,
        hasServices_jump_certificate_uri VARCHAR(255) NULL,
        hasServices_unlock_name VARCHAR(255) NULL,
        hasServices_unlock_type VARCHAR(255) NULL,
        hasServices_unlock_isVerified BOOLEAN,
        hasServices_unlock_isApproved BOOLEAN,
        hasServices_unlock_certificate_uri VARCHAR(255) NULL,
        company_id VARCHAR(255) NULL,
        company_status VARCHAR(255) NULL
    );
"""

_users_colum_names = [
    "_id",
    "name",
    "email",
    "about",
    "phoneNumber",
    "criminalStatus",
    "isClient",
    "IsSpecialist",
    "isValidCertification",
    "isActive",
    "isDeleted",
    "registerType",
    "profileImg_url",
    "licenseImg_url",
    "insuranceImg_url",
    "date",
    "__v",
    "hasServices_refuel_name",
    "hasServices_refuel_type",
    "hasServices_refuel_isVerified",
    "hasServices_refuel_isApproved",
    "hasServices_tire_change_name",
    "hasServices_tire_change_type",
    "hasServices_tire_change_isVerified",
    "hasServices_tire_change_isApproved",
    "hasServices_tire_change_certificate_uri",
    "hasServices_jump_name",
    "hasServices_jump_type",
    "hasServices_jump_isVerified",
    "hasServices_jump_isApproved",
    "hasServices_jump_certificate_uri",
    "hasServices_unlock_name",
    "hasServices_unlock_type",
    "hasServices_unlock_isVerified",
    "hasServices_unlock_isApproved",
    "hasServices_unlock_certificate_uri",
    "company_id",
    "company_status",
]
